# syntax=docker/dockerfile:1
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG FFM_URL
ARG FFM_PACKAGE
ARG FFM_SOURCE=dev
ARG INSTALL_LLVM=yes
ARG LLVM_REF=amd/dev/jebyrnes/PipelinedSchedulerTriton7
ARG TRITON_REF=shared/AIDayStaging

COPY --chmod=755 .github/ffm/build_llvm_triton.sh /root/build_llvm_triton.sh

RUN --mount=type=secret,id=netrc,target=/root/.netrc set -eux; \
    export HOME=/root; \
    mkdir -p /ffm; cd /ffm; \
    wget "${FFM_URL}"; \
    test -s "${FFM_PACKAGE}"; \
    tar -xf "${FFM_PACKAGE}"; \
    pip install PyYAML; \
    if [ "${FFM_SOURCE}" = "dev" ]; then \
        [ -d lib ] || mkdir -p lib; \
        if [ -f libhsakmtmodel.so ]; then mv libhsakmtmodel.so lib/; fi; \
    fi

COPY --chmod=755 .github/ffm/ffmlite_env.sh /ffm/ffmlite_env.sh
RUN grep -q "ffmlite_env.sh" /root/.bashrc \
    || echo "source /ffm/ffmlite_env.sh" >> /root/.bashrc

RUN --mount=type=secret,id=amd_lightning_token,target=/run/secrets/amd_lightning_token set -eu; \
    if [ "${INSTALL_LLVM}" = "yes" ]; then \
        TOKEN="$(cat /run/secrets/amd_lightning_token)"; \
        cd /root; \
        git -c "http.https://github.com/.extraheader=AUTHORIZATION: bearer ${TOKEN}" \
            clone -b "${LLVM_REF}" https://github.com/AMD-Lightning-Internal/llvm-project.git llvm-project; \
    else \
        echo "INSTALL_LLVM=no - skipping llvm-project clone"; \
    fi

RUN --mount=type=secret,id=amd_triton_token,target=/run/secrets/amd_triton_token set -eu; \
    TOKEN="$(cat /run/secrets/amd_triton_token)"; \
    cd /root; \
    git -c "http.https://github.com/.extraheader=AUTHORIZATION: bearer ${TOKEN}" \
        clone -b "${TRITON_REF}" https://github.com/AMD-Triton/triton-mi450.git triton; \
    cd /root/triton; \
    pip install -r python/requirements.txt; \
    pip install -U nanobind numpy scipy pandas matplotlib einops pytest pytest-xdist pytest-repeat expecttest pylama pre-commit clang-format; \
    if [ "${INSTALL_LLVM}" = "yes" ]; then \
        bash /root/build_llvm_triton.sh; \
    else \
        pip install -e .; \
    fi

ENV AITER_USE_SYSTEM_TRITON=1

COPY . /root/aiter
RUN set -eux; \
    cd /root/aiter; \
    pip install -r requirements.txt; \
    pip install -e . --no-build-isolation

WORKDIR /root
